### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by zaisahil** [frankandoak/silo#1]
I have cloned your project but I am unable to start it. Can you please provide proper guideline step by step on how to run your project on Windows based computer using XAMPP?

Thank you.

-Saeed

**Comment by dav-m85** [comment]
Hi @zaisahil, the project is still in a WIP state right now, the main missing part being the UI (we proxy the call to our legacy WMS to provide the UI).

I'll do my best to provide you with some guideline to help you have it running, but be aware that it is not entirely user friendly yet.

**Comment by zaisahil** [comment]
Thanks for the reply @dav-m85. 

Well, I hope UI will be completed soon. 

I will wait for your guidelines. 

-Saeed
